// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: sui/rpc/v2/jwk.proto

package rpcv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Key to uniquely identify a JWK.
type JwkId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The issuer or identity of the OIDC provider.
	Iss *string `protobuf:"bytes,1,opt,name=iss,proto3,oneof" json:"iss,omitempty"`
	// A key ID used to uniquely identify a key from an OIDC provider.
	Kid           *string `protobuf:"bytes,2,opt,name=kid,proto3,oneof" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwkId) Reset() {
	*x = JwkId{}
	mi := &file_sui_rpc_v2_jwk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwkId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwkId) ProtoMessage() {}

func (x *JwkId) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_jwk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwkId.ProtoReflect.Descriptor instead.
func (*JwkId) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_jwk_proto_rawDescGZIP(), []int{0}
}

func (x *JwkId) GetIss() string {
	if x != nil && x.Iss != nil {
		return *x.Iss
	}
	return ""
}

func (x *JwkId) GetKid() string {
	if x != nil && x.Kid != nil {
		return *x.Kid
	}
	return ""
}

// A JSON web key.
//
// Struct that contains info for a JWK. A list of them for different kinds can
// be retrieved from the JWK endpoint (for example, <https://www.googleapis.com/oauth2/v3/certs>).
// The JWK is used to verify the JWT token.
type Jwk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key type parameter, https://datatracker.ietf.org/doc/html/rfc7517#section-4.1.
	Kty *string `protobuf:"bytes,1,opt,name=kty,proto3,oneof" json:"kty,omitempty"`
	// RSA public exponent, https://datatracker.ietf.org/doc/html/rfc7517#section-9.3.
	E *string `protobuf:"bytes,2,opt,name=e,proto3,oneof" json:"e,omitempty"`
	// RSA modulus, https://datatracker.ietf.org/doc/html/rfc7517#section-9.3.
	N *string `protobuf:"bytes,3,opt,name=n,proto3,oneof" json:"n,omitempty"`
	// Algorithm parameter, https://datatracker.ietf.org/doc/html/rfc7517#section-4.4.
	Alg           *string `protobuf:"bytes,4,opt,name=alg,proto3,oneof" json:"alg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwk) Reset() {
	*x = Jwk{}
	mi := &file_sui_rpc_v2_jwk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwk) ProtoMessage() {}

func (x *Jwk) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_jwk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwk.ProtoReflect.Descriptor instead.
func (*Jwk) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_jwk_proto_rawDescGZIP(), []int{1}
}

func (x *Jwk) GetKty() string {
	if x != nil && x.Kty != nil {
		return *x.Kty
	}
	return ""
}

func (x *Jwk) GetE() string {
	if x != nil && x.E != nil {
		return *x.E
	}
	return ""
}

func (x *Jwk) GetN() string {
	if x != nil && x.N != nil {
		return *x.N
	}
	return ""
}

func (x *Jwk) GetAlg() string {
	if x != nil && x.Alg != nil {
		return *x.Alg
	}
	return ""
}

var File_sui_rpc_v2_jwk_proto protoreflect.FileDescriptor

var file_sui_rpc_v2_jwk_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x73, 0x75, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x2f, 0x6a, 0x77, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x32, 0x22, 0x45, 0x0a, 0x05, 0x4a, 0x77, 0x6b, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x03, 0x69,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x69, 0x73, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6b, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x03, 0x6b, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x69, 0x73,
	0x73, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b, 0x69, 0x64, 0x22, 0x75, 0x0a, 0x03, 0x4a, 0x77, 0x6b,
	0x12, 0x15, 0x0a, 0x03, 0x6b, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x03, 0x6b, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x01, 0x65, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x01, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a,
	0x03, 0x61, 0x6c, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x03, 0x61, 0x6c,
	0x67, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b, 0x74, 0x79, 0x42, 0x04, 0x0a, 0x02,
	0x5f, 0x65, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x61, 0x6c, 0x67,
	0x42, 0xb3, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x76, 0x32, 0x42, 0x08, 0x4a, 0x77, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x74, 0x6f, 0x72,
	0x6b, 0x2d, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x6b, 0x2d, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x75,
	0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x3b, 0x72, 0x70, 0x63, 0x76, 0x32, 0xa2, 0x02,
	0x03, 0x53, 0x52, 0x58, 0xaa, 0x02, 0x0a, 0x53, 0x75, 0x69, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x56,
	0x32, 0xca, 0x02, 0x0a, 0x53, 0x75, 0x69, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x32, 0xe2, 0x02,
	0x16, 0x53, 0x75, 0x69, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x53, 0x75, 0x69, 0x3a, 0x3a, 0x52,
	0x70, 0x63, 0x3a, 0x3a, 0x56, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sui_rpc_v2_jwk_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_jwk_proto_rawDescData []byte
)

func file_sui_rpc_v2_jwk_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_jwk_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_jwk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_jwk_proto_rawDesc), len(file_sui_rpc_v2_jwk_proto_rawDesc)))
	})
	return file_sui_rpc_v2_jwk_proto_rawDescData
}

var file_sui_rpc_v2_jwk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sui_rpc_v2_jwk_proto_goTypes = []any{
	(*JwkId)(nil), // 0: sui.rpc.v2.JwkId
	(*Jwk)(nil),   // 1: sui.rpc.v2.Jwk
}
var file_sui_rpc_v2_jwk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_jwk_proto_init() }
func file_sui_rpc_v2_jwk_proto_init() {
	if File_sui_rpc_v2_jwk_proto != nil {
		return
	}
	file_sui_rpc_v2_jwk_proto_msgTypes[0].OneofWrappers = []any{}
	file_sui_rpc_v2_jwk_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_jwk_proto_rawDesc), len(file_sui_rpc_v2_jwk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_jwk_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_jwk_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_jwk_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_jwk_proto = out.File
	file_sui_rpc_v2_jwk_proto_goTypes = nil
	file_sui_rpc_v2_jwk_proto_depIdxs = nil
}
