// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: sui/rpc/v2/query_options.proto

package rpcv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ordering for the returned result set.
type Ordering int32

const (
	// Return results in increasing cursor order.
	Ordering_ORDERING_ASCENDING Ordering = 0
	// Return results in decreasing cursor order.
	Ordering_ORDERING_DESCENDING Ordering = 1
)

// Enum value maps for Ordering.
var (
	Ordering_name = map[int32]string{
		0: "ORDERING_ASCENDING",
		1: "ORDERING_DESCENDING",
	}
	Ordering_value = map[string]int32{
		"ORDERING_ASCENDING":  0,
		"ORDERING_DESCENDING": 1,
	}
)

func (x Ordering) Enum() *Ordering {
	p := new(Ordering)
	*p = x
	return p
}

func (x Ordering) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ordering) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2_query_options_proto_enumTypes[0].Descriptor()
}

func (Ordering) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2_query_options_proto_enumTypes[0]
}

func (x Ordering) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ordering.Descriptor instead.
func (Ordering) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2_query_options_proto_rawDescGZIP(), []int{0}
}

// Reason the server stopped this query response.
type QueryEndReason int32

const (
	// The stop reason was not specified.
	QueryEndReason_QUERY_END_REASON_UNKNOWN QueryEndReason = 0
	// The response reached the requested item limit. The final matching item's
	// frame carries `QueryEnd` and the final watermark. Resume from that frame's
	// `Watermark.cursor` to continue reading the same effective interval.
	QueryEndReason_QUERY_END_REASON_ITEM_LIMIT QueryEndReason = 1
	// The response reached the server's per-request bucket-fetch budget for
	// filtered scans before reaching the effective interval bound. The terminal
	// frame carries no item. Its watermark cursor is the authoritative scan
	// frontier from which to resume.
	QueryEndReason_QUERY_END_REASON_SCAN_LIMIT QueryEndReason = 2
	// The scan reached a requested checkpoint range bound. The terminal frame
	// carries no item.
	QueryEndReason_QUERY_END_REASON_CHECKPOINT_BOUND QueryEndReason = 3
	// The scan reached an exclusive cursor bound. The terminal frame carries no
	// item. Its watermark cursor represents that resolved bound without claiming
	// that its containing checkpoint was fully covered.
	QueryEndReason_QUERY_END_REASON_CURSOR_BOUND QueryEndReason = 4
	// The scan reached the currently indexed ledger tip. The terminal frame
	// carries no item.
	QueryEndReason_QUERY_END_REASON_LEDGER_TIP QueryEndReason = 5
)

// Enum value maps for QueryEndReason.
var (
	QueryEndReason_name = map[int32]string{
		0: "QUERY_END_REASON_UNKNOWN",
		1: "QUERY_END_REASON_ITEM_LIMIT",
		2: "QUERY_END_REASON_SCAN_LIMIT",
		3: "QUERY_END_REASON_CHECKPOINT_BOUND",
		4: "QUERY_END_REASON_CURSOR_BOUND",
		5: "QUERY_END_REASON_LEDGER_TIP",
	}
	QueryEndReason_value = map[string]int32{
		"QUERY_END_REASON_UNKNOWN":          0,
		"QUERY_END_REASON_ITEM_LIMIT":       1,
		"QUERY_END_REASON_SCAN_LIMIT":       2,
		"QUERY_END_REASON_CHECKPOINT_BOUND": 3,
		"QUERY_END_REASON_CURSOR_BOUND":     4,
		"QUERY_END_REASON_LEDGER_TIP":       5,
	}
)

func (x QueryEndReason) Enum() *QueryEndReason {
	p := new(QueryEndReason)
	*p = x
	return p
}

func (x QueryEndReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryEndReason) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2_query_options_proto_enumTypes[1].Descriptor()
}

func (QueryEndReason) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2_query_options_proto_enumTypes[1]
}

func (x QueryEndReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryEndReason.Descriptor instead.
func (QueryEndReason) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2_query_options_proto_rawDescGZIP(), []int{1}
}

// Cursor-bounded query options.
//
// `after` and `before` are canonical ledger-position bounds, not
// ordering-relative cursors. `after` always excludes items at or below that
// cursor, and `before` always excludes items at or above that cursor. Ordering
// only controls the order of returned items within the resulting open interval.
//
// When a request also specifies a checkpoint range, cursor bounds and
// checkpoint bounds compose by intersection: results come only from ledger
// positions inside both. Checkpoint bounds are likewise canonical and
// ordering-independent.
//
// For example, with `after = A`, `before = B`, `ordering = DESCENDING`, and
// `limit = N`, the response contains up to N matching items in descending
// order from the interval `(A, B)`. If the response ends with
// `QUERY_END_REASON_ITEM_LIMIT`, resume by keeping `after = A` and setting
// `before` to the last `Watermark.cursor` received. That cursor is the
// lowest position reached in ledger order, so it becomes the next exclusive
// upper bound.
type QueryOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of items to return. Each method applies its own default
	// and maximum. QueryEnd does not count against this limit.
	Limit *uint32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Opaque exclusive lower bound. Results must be strictly after this cursor in
	// canonical ledger order.
	After []byte `protobuf:"bytes,2,opt,name=after,proto3,oneof" json:"after,omitempty"`
	// Opaque exclusive upper bound. Results must be strictly before this cursor
	// in canonical ledger order.
	Before []byte `protobuf:"bytes,3,opt,name=before,proto3,oneof" json:"before,omitempty"`
	// Ordering for returned results. Defaults to ASCENDING.
	//
	// Ordering only controls the order of results within the bounded interval;
	// cursor bounds keep the same meaning for ascending and descending reads.
	Ordering      *Ordering `protobuf:"varint,4,opt,name=ordering,proto3,enum=sui.rpc.v2.Ordering,oneof" json:"ordering,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_sui_rpc_v2_query_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_query_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_query_options_proto_rawDescGZIP(), []int{0}
}

func (x *QueryOptions) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *QueryOptions) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *QueryOptions) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *QueryOptions) GetOrdering() Ordering {
	if x != nil && x.Ordering != nil {
		return *x.Ordering
	}
	return Ordering_ORDERING_ASCENDING
}

// Progress marker for a query scan. Carried on every response frame, whether or
// not the frame delivers a matching item. Watermarks never regress in the
// requested ordering, but consecutive frames may carry the same watermark when
// additional work does not advance the safe resume frontier.
type Watermark struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque cursor at this scan position. Set on every watermark. Use as
	// `options.after` (ascending) or `options.before` (descending) on the next
	// request to resume from here. The most recently received cursor is always
	// the safe resume point.
	Cursor []byte `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	// The inclusive boundary checkpoint that the scan has fully covered within
	// the request's effective interval, in the request's ordering direction: an
	// ascending scan has emitted every matching item in the interval at
	// checkpoints `<= checkpoint` (strictly greater ones may still hold
	// matches); a descending scan has emitted every matching item in the
	// interval at checkpoints `>= checkpoint`. This boundary never regresses in
	// the scan direction, but it may repeat while the cursor advances.
	//
	// Unset until the scan's first checkpoint is fully covered. For example, a
	// scan resumed from a cursor that lands mid-checkpoint leaves this unset
	// until the next checkpoint boundary in the scan direction is fully covered.
	// A watermark still has a valid resume cursor while this field is unset.
	Checkpoint    *uint64 `protobuf:"varint,2,opt,name=checkpoint,proto3,oneof" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Watermark) Reset() {
	*x = Watermark{}
	mi := &file_sui_rpc_v2_query_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Watermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watermark) ProtoMessage() {}

func (x *Watermark) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_query_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watermark.ProtoReflect.Descriptor instead.
func (*Watermark) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_query_options_proto_rawDescGZIP(), []int{1}
}

func (x *Watermark) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Watermark) GetCheckpoint() uint64 {
	if x != nil && x.Checkpoint != nil {
		return *x.Checkpoint
	}
	return 0
}

// Marker for the final frame of a successful query stream. Every successful
// stream sets `QueryEnd` on exactly one frame, after which no further frames
// are sent. That frame always carries the final watermark. For `ItemLimit`, it
// also carries the final matching item; for every other reason it carries no
// item. A ScanLimit terminal watermark may repeat the previous frame's cursor
// when its authoritative scan frontier was already emitted; this does not
// repeat an item.
//
// A stream that fails or is cancelled terminates with a gRPC status and does
// not send `QueryEnd`.
type QueryEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reason this response stopped.
	Reason        *QueryEndReason `protobuf:"varint,1,opt,name=reason,proto3,enum=sui.rpc.v2.QueryEndReason,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEnd) Reset() {
	*x = QueryEnd{}
	mi := &file_sui_rpc_v2_query_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEnd) ProtoMessage() {}

func (x *QueryEnd) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_query_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEnd.ProtoReflect.Descriptor instead.
func (*QueryEnd) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_query_options_proto_rawDescGZIP(), []int{2}
}

func (x *QueryEnd) GetReason() QueryEndReason {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return QueryEndReason_QUERY_END_REASON_UNKNOWN
}

var File_sui_rpc_v2_query_options_proto protoreflect.FileDescriptor

var file_sui_rpc_v2_query_options_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x73, 0x75, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x2f, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x22, 0xc4, 0x01, 0x0a,
	0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x02, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x35, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x03, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x22, 0x67, 0x0a, 0x09, 0x57, 0x61, 0x74, 0x65, 0x72, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x1b, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a,
	0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x01, 0x52, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x08,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x64, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x64, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2a, 0x3b, 0x0a, 0x08,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x52, 0x44, 0x45,
	0x52, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x53, 0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x17, 0x0a, 0x13, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x44, 0x45, 0x53,
	0x43, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x2a, 0xdb, 0x01, 0x0a, 0x0e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x45, 0x6e, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x18,
	0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x51, 0x55,
	0x45, 0x52, 0x59, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x49,
	0x54, 0x45, 0x4d, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x51,
	0x55, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f,
	0x53, 0x43, 0x41, 0x4e, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x02, 0x12, 0x25, 0x0a, 0x21,
	0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e,
	0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x42, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x03, 0x12, 0x21, 0x0a, 0x1d, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x45, 0x4e, 0x44,
	0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x43, 0x55, 0x52, 0x53, 0x4f, 0x52, 0x5f, 0x42,
	0x4f, 0x55, 0x4e, 0x44, 0x10, 0x04, 0x12, 0x1f, 0x0a, 0x1b, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f,
	0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x41, 0x53, 0x4f, 0x4e, 0x5f, 0x4c, 0x45, 0x44, 0x47, 0x45,
	0x52, 0x5f, 0x54, 0x49, 0x50, 0x10, 0x05, 0x42, 0xbc, 0x01, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x42, 0x11, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x74, 0x6f, 0x72,
	0x6b, 0x2d, 0x4f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x6b, 0x2d, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x75,
	0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x3b, 0x72, 0x70, 0x63, 0x76, 0x32, 0xa2, 0x02,
	0x03, 0x53, 0x52, 0x58, 0xaa, 0x02, 0x0a, 0x53, 0x75, 0x69, 0x2e, 0x52, 0x70, 0x63, 0x2e, 0x56,
	0x32, 0xca, 0x02, 0x0a, 0x53, 0x75, 0x69, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x32, 0xe2, 0x02,
	0x16, 0x53, 0x75, 0x69, 0x5c, 0x52, 0x70, 0x63, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x53, 0x75, 0x69, 0x3a, 0x3a, 0x52,
	0x70, 0x63, 0x3a, 0x3a, 0x56, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_sui_rpc_v2_query_options_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_query_options_proto_rawDescData []byte
)

func file_sui_rpc_v2_query_options_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_query_options_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_query_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_query_options_proto_rawDesc), len(file_sui_rpc_v2_query_options_proto_rawDesc)))
	})
	return file_sui_rpc_v2_query_options_proto_rawDescData
}

var file_sui_rpc_v2_query_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sui_rpc_v2_query_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sui_rpc_v2_query_options_proto_goTypes = []any{
	(Ordering)(0),        // 0: sui.rpc.v2.Ordering
	(QueryEndReason)(0),  // 1: sui.rpc.v2.QueryEndReason
	(*QueryOptions)(nil), // 2: sui.rpc.v2.QueryOptions
	(*Watermark)(nil),    // 3: sui.rpc.v2.Watermark
	(*QueryEnd)(nil),     // 4: sui.rpc.v2.QueryEnd
}
var file_sui_rpc_v2_query_options_proto_depIdxs = []int32{
	0, // 0: sui.rpc.v2.QueryOptions.ordering:type_name -> sui.rpc.v2.Ordering
	1, // 1: sui.rpc.v2.QueryEnd.reason:type_name -> sui.rpc.v2.QueryEndReason
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_query_options_proto_init() }
func file_sui_rpc_v2_query_options_proto_init() {
	if File_sui_rpc_v2_query_options_proto != nil {
		return
	}
	file_sui_rpc_v2_query_options_proto_msgTypes[0].OneofWrappers = []any{}
	file_sui_rpc_v2_query_options_proto_msgTypes[1].OneofWrappers = []any{}
	file_sui_rpc_v2_query_options_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_query_options_proto_rawDesc), len(file_sui_rpc_v2_query_options_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_query_options_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_query_options_proto_depIdxs,
		EnumInfos:         file_sui_rpc_v2_query_options_proto_enumTypes,
		MessageInfos:      file_sui_rpc_v2_query_options_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_query_options_proto = out.File
	file_sui_rpc_v2_query_options_proto_goTypes = nil
	file_sui_rpc_v2_query_options_proto_depIdxs = nil
}
