// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sui/rpc/v2/subscription_service.proto

package rpcv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionService_SubscribeCheckpoints_FullMethodName  = "/sui.rpc.v2.SubscriptionService/SubscribeCheckpoints"
	SubscriptionService_SubscribeTransactions_FullMethodName = "/sui.rpc.v2.SubscriptionService/SubscribeTransactions"
	SubscriptionService_SubscribeEvents_FullMethodName       = "/sui.rpc.v2.SubscriptionService/SubscribeEvents"
)

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubscriptionService provides filtered, real-time streams of checkpoints,
// transactions, and events.
//
// Each Subscribe API pairs with the LedgerService List API of the same name:
// requests take the same filter message, and responses carry the same item
// and watermark shapes with identical cursor semantics.
//
// Subscriptions do not support resumption. A new subscription always begins
// at the current tip of the chain as seen by the server (the latest executed
// checkpoint). To recover data missed between subscriptions, replay the gap
// with the paired List API: pass the last received `Watermark.cursor` as
// `options.after` on the List request (for checkpoints, pass the last
// received `cursor + 1` as `start_checkpoint`). The List scan reads from the
// indexed tip, which may trail the subscription's start position; repeat the
// List call as the index advances until the replay reaches the position
// established by the subscription's first frame.
//
// A subscription behaves like an unbounded ascending scan: every frame
// carries the subscriber's resume point, and progress advances as
// checkpoints are fully covered. Two delivery guarantees keep sparse
// filters live: the first frame on a filtered subscription is a
// progress-only frame establishing the stream's start position, and
// progress continues to advance with bounded staleness even when no item
// matches.
//
// Subscription streams have no successful end: they run until cancelled by
// the client or terminated by the server with a gRPC status.
type SubscriptionServiceClient interface {
	// Subscribe to the stream of checkpoints.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields checkpoints matching the filter as they are executed.
	// A checkpoint matches if any transaction it contains satisfies the
	// filter.
	SubscribeCheckpoints(ctx context.Context, in *SubscribeCheckpointsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeCheckpointsResponse], error)
	// Subscribe to the stream of transactions.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields transactions matching the filter as they are executed.
	SubscribeTransactions(ctx context.Context, in *SubscribeTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeTransactionsResponse], error)
	// Subscribe to the stream of events.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields events matching the filter as they are emitted.
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEventsResponse], error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) SubscribeCheckpoints(ctx context.Context, in *SubscribeCheckpointsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeCheckpointsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[0], SubscriptionService_SubscribeCheckpoints_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeCheckpointsRequest, SubscribeCheckpointsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_SubscribeCheckpointsClient = grpc.ServerStreamingClient[SubscribeCheckpointsResponse]

func (c *subscriptionServiceClient) SubscribeTransactions(ctx context.Context, in *SubscribeTransactionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeTransactionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[1], SubscriptionService_SubscribeTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTransactionsRequest, SubscribeTransactionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_SubscribeTransactionsClient = grpc.ServerStreamingClient[SubscribeTransactionsResponse]

func (c *subscriptionServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[2], SubscriptionService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, SubscribeEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_SubscribeEventsClient = grpc.ServerStreamingClient[SubscribeEventsResponse]

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility.
//
// SubscriptionService provides filtered, real-time streams of checkpoints,
// transactions, and events.
//
// Each Subscribe API pairs with the LedgerService List API of the same name:
// requests take the same filter message, and responses carry the same item
// and watermark shapes with identical cursor semantics.
//
// Subscriptions do not support resumption. A new subscription always begins
// at the current tip of the chain as seen by the server (the latest executed
// checkpoint). To recover data missed between subscriptions, replay the gap
// with the paired List API: pass the last received `Watermark.cursor` as
// `options.after` on the List request (for checkpoints, pass the last
// received `cursor + 1` as `start_checkpoint`). The List scan reads from the
// indexed tip, which may trail the subscription's start position; repeat the
// List call as the index advances until the replay reaches the position
// established by the subscription's first frame.
//
// A subscription behaves like an unbounded ascending scan: every frame
// carries the subscriber's resume point, and progress advances as
// checkpoints are fully covered. Two delivery guarantees keep sparse
// filters live: the first frame on a filtered subscription is a
// progress-only frame establishing the stream's start position, and
// progress continues to advance with bounded staleness even when no item
// matches.
//
// Subscription streams have no successful end: they run until cancelled by
// the client or terminated by the server with a gRPC status.
type SubscriptionServiceServer interface {
	// Subscribe to the stream of checkpoints.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields checkpoints matching the filter as they are executed.
	// A checkpoint matches if any transaction it contains satisfies the
	// filter.
	SubscribeCheckpoints(*SubscribeCheckpointsRequest, grpc.ServerStreamingServer[SubscribeCheckpointsResponse]) error
	// Subscribe to the stream of transactions.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields transactions matching the filter as they are executed.
	SubscribeTransactions(*SubscribeTransactionsRequest, grpc.ServerStreamingServer[SubscribeTransactionsResponse]) error
	// Subscribe to the stream of events.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields events matching the filter as they are emitted.
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[SubscribeEventsResponse]) error
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionServiceServer struct{}

func (UnimplementedSubscriptionServiceServer) SubscribeCheckpoints(*SubscribeCheckpointsRequest, grpc.ServerStreamingServer[SubscribeCheckpointsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeCheckpoints not implemented")
}
func (UnimplementedSubscriptionServiceServer) SubscribeTransactions(*SubscribeTransactionsRequest, grpc.ServerStreamingServer[SubscribeTransactionsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTransactions not implemented")
}
func (UnimplementedSubscriptionServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[SubscribeEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}
func (UnimplementedSubscriptionServiceServer) testEmbeddedByValue()                             {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_SubscribeCheckpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeCheckpointsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).SubscribeCheckpoints(m, &grpc.GenericServerStream[SubscribeCheckpointsRequest, SubscribeCheckpointsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_SubscribeCheckpointsServer = grpc.ServerStreamingServer[SubscribeCheckpointsResponse]

func _SubscriptionService_SubscribeTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).SubscribeTransactions(m, &grpc.GenericServerStream[SubscribeTransactionsRequest, SubscribeTransactionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_SubscribeTransactionsServer = grpc.ServerStreamingServer[SubscribeTransactionsResponse]

func _SubscriptionService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, SubscribeEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SubscriptionService_SubscribeEventsServer = grpc.ServerStreamingServer[SubscribeEventsResponse]

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sui.rpc.v2.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCheckpoints",
			Handler:       _SubscriptionService_SubscribeCheckpoints_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTransactions",
			Handler:       _SubscriptionService_SubscribeTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _SubscriptionService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sui/rpc/v2/subscription_service.proto",
}
