 import os

def get_package_names(parent_dir):
    package_names = [d for d in os.listdir(parent_dir) if os.path.isdir(os.path.join(parent_dir, d))]
    return sorted(package_names)

def generate_go_file(directories, output_file):
    with open(output_file, 'w') as f:
        f.write("package data_provider\n\n")
        f.write("// Autogenerated by generate_data_provider_import_file.py\n")
        for dir in directories:
            f.write(f'import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/{dir}"\n')


def main():
    parent_dir = './apps/lib/data_provider/sources'
    output_file = './apps/lib/data_provider/import_sources.go'

    package_names = get_package_names(parent_dir)
    generate_go_file(package_names, output_file)

    print(f"Go file generated successfully at {output_file}")

if __name__ == "__main__":
    main()
