// Code initially generated by gen.go.
// This file defines the configuration for the data source.

package monadgasfees

import "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/types"

type MonadGasFeesConfig struct {
	DataSource      types.DataSourceId `json:"dataSource"` // required for all Data Provider Sources
	RpcEndpoint     string             `json:"rpcEndpoint"` // Monad RPC endpoint URL
	UpdateFrequency string             `json:"updateFrequency"` // How often to fetch gas fee data
	BlockWindow     int                `json:"blockWindow"` // Number of recent blocks to analyze for gas fees
}
