// Code initially generated by gen.go.
// This file initializes the data source and registers it, allowing it to be built by the DataProviderRunner.

package monadgasfees

import (
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources"
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/types"
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/utils"
	"github.com/mitchellh/mapstructure"
)

var MonadGasFeesDataSourceId types.DataSourceId = types.DataSourceId(utils.GetCurrentDirName())

type monadGasFeesDataSourceFactory struct{}

func (f *monadGasFeesDataSourceFactory) Build(sourceConfig types.DataProviderSourceConfig) types.DataSource {
	return newMonadGasFeesDataSource(sourceConfig)
}

func init() {
	sources.RegisterDataSourceFactory(MonadGasFeesDataSourceId, &monadGasFeesDataSourceFactory{})
}

// assert we're satisfying our interfaces
var (
	_ types.DataSource        = (*monadGasFeesDataSource)(nil)
	_ types.DataSourceFactory = (*monadGasFeesDataSourceFactory)(nil)
)

func GetSourceSpecificConfig(sourceConfig types.DataProviderSourceConfig) (MonadGasFeesConfig, error) {
	var config MonadGasFeesConfig
	err := mapstructure.Decode(sourceConfig.Config, &config)

	return config, err
}
