dir: '{{.InterfaceDirRelative}}/mocks'
structname: Mock{{.InterfaceName | camelcase | firstUpper}}
filename: "mock_{{.InterfaceName | snakecase | lower}}.go"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/Stork-Oracle/stork-external/apps/chain_pusher/pkg/types:
    interfaces:
      ContractInteractor:
