[package]
name = "stork-sdk"
version = "0.0.3"
edition = "2021"
description = "A Solana SDK for Stork Protocol"
license = "Apache-2.0"
repository = "https://github.com/Stork-Oracle/stork-external"


[lib]
crate-type = ["lib"]
name = "stork_sdk"

[dependencies]
anchor-lang = "0.30.1"
