// Code initially generated by gen.go.

package raydiumclmm

import "github.com/Stork-Oracle/stork-external/apps/data_provider/pkg/types"

type RaydiumCLMMConfig struct {
	DataSource      types.DataSourceID `json:"dataSource"`
	UpdateFrequency string             `json:"updateFrequency"`
	HttpProviderUrl string             `json:"httpProviderUrl"`
	ContractAddress string             `json:"contractAddress"`
}
