// Code generated by https://github.com/henrymbaldwin/solana-anchor-go. DO NOT EDIT.

package bindings

import (
	"errors"

	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateStorkEvmPublicKey is the `update_stork_evm_public_key` instruction.
type UpdateStorkEvmPublicKey struct {
	NewStorkEvmPublicKey *[20]uint8

	// [0] = [WRITE] config
	//
	// [1] = [SIGNER] owner
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateStorkEvmPublicKeyInstructionBuilder creates a new `UpdateStorkEvmPublicKey` instruction builder.
func NewUpdateStorkEvmPublicKeyInstructionBuilder() *UpdateStorkEvmPublicKey {
	nd := &UpdateStorkEvmPublicKey{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetNewStorkEvmPublicKey sets the "new_stork_evm_public_key" parameter.
func (inst *UpdateStorkEvmPublicKey) SetNewStorkEvmPublicKey(new_stork_evm_public_key [20]uint8) *UpdateStorkEvmPublicKey {
	inst.NewStorkEvmPublicKey = &new_stork_evm_public_key
	return inst
}

// SetConfigAccount sets the "config" account.
func (inst *UpdateStorkEvmPublicKey) SetConfigAccount(config ag_solanago.PublicKey) *UpdateStorkEvmPublicKey {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(config).WRITE()
	return inst
}

func (inst *UpdateStorkEvmPublicKey) findFindConfigAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: stork_config
	seeds = append(seeds, []byte{byte(0x73), byte(0x74), byte(0x6f), byte(0x72), byte(0x6b), byte(0x5f), byte(0x63), byte(0x6f), byte(0x6e), byte(0x66), byte(0x69), byte(0x67)})

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindConfigAddressWithBumpSeed calculates Config account address with given seeds and a known bump seed.
func (inst *UpdateStorkEvmPublicKey) FindConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindConfigAddress(bumpSeed)
	return
}

func (inst *UpdateStorkEvmPublicKey) MustFindConfigAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindConfigAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindConfigAddress finds Config account address with given seeds.
func (inst *UpdateStorkEvmPublicKey) FindConfigAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindConfigAddress(0)
	return
}

func (inst *UpdateStorkEvmPublicKey) MustFindConfigAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindConfigAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetConfigAccount gets the "config" account.
func (inst *UpdateStorkEvmPublicKey) GetConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetOwnerAccount sets the "owner" account.
func (inst *UpdateStorkEvmPublicKey) SetOwnerAccount(owner ag_solanago.PublicKey) *UpdateStorkEvmPublicKey {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(owner).SIGNER()
	return inst
}

// GetOwnerAccount gets the "owner" account.
func (inst *UpdateStorkEvmPublicKey) GetOwnerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst UpdateStorkEvmPublicKey) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateStorkEvmPublicKey,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateStorkEvmPublicKey) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateStorkEvmPublicKey) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewStorkEvmPublicKey == nil {
			return errors.New("NewStorkEvmPublicKey parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Config is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Owner is not set")
		}
	}
	return nil
}

func (inst *UpdateStorkEvmPublicKey) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateStorkEvmPublicKey")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("    NewStorkEvmPublicKey", *inst.NewStorkEvmPublicKey))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("config", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta(" owner", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj UpdateStorkEvmPublicKey) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewStorkEvmPublicKey` param:
	err = encoder.Encode(obj.NewStorkEvmPublicKey)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UpdateStorkEvmPublicKey) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewStorkEvmPublicKey`:
	err = decoder.Decode(&obj.NewStorkEvmPublicKey)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateStorkEvmPublicKeyInstruction declares a new UpdateStorkEvmPublicKey instruction with the provided parameters and accounts.
func NewUpdateStorkEvmPublicKeyInstruction(
	// Parameters:
	new_stork_evm_public_key [20]uint8,
	// Accounts:
	config ag_solanago.PublicKey,
	owner ag_solanago.PublicKey) *UpdateStorkEvmPublicKey {
	return NewUpdateStorkEvmPublicKeyInstructionBuilder().
		SetNewStorkEvmPublicKey(new_stork_evm_public_key).
		SetConfigAccount(config).
		SetOwnerAccount(owner)
}
