// Code initially generated by gen.go.
// This file defines the configuration for the data source.

package monadblockdata

import "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/types"

type MonadBlockDataConfig struct {
	DataSource      types.DataSourceId `json:"dataSource"` // required for all Data Provider Sources
	RpcEndpoint     string             `json:"rpcEndpoint"` // Monad RPC endpoint URL
	UpdateFrequency string             `json:"updateFrequency"` // How often to fetch new block data
	BlockTimeWindow int                `json:"blockTimeWindow"` // Number of recent blocks to analyze for block time
}
