// Code initially generated by gen.go.
// This file initializes the data source and registers it, allowing it to be built by the DataProviderRunner.

package monadblockdata

import (
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources"
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/types"
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/utils"
	"github.com/mitchellh/mapstructure"
)

var MonadBlockDataDataSourceId types.DataSourceId = types.DataSourceId(utils.GetCurrentDirName())

type monadBlockDataDataSourceFactory struct{}

func (f *monadBlockDataDataSourceFactory) Build(sourceConfig types.DataProviderSourceConfig) types.DataSource {
	return newMonadBlockDataDataSource(sourceConfig)
}

func init() {
	sources.RegisterDataSourceFactory(MonadBlockDataDataSourceId, &monadBlockDataDataSourceFactory{})
}

// assert we're satisfying our interfaces
var (
	_ types.DataSource        = (*monadBlockDataDataSource)(nil)
	_ types.DataSourceFactory = (*monadBlockDataDataSourceFactory)(nil)
)

func GetSourceSpecificConfig(sourceConfig types.DataProviderSourceConfig) (MonadBlockDataConfig, error) {
	var config MonadBlockDataConfig
	err := mapstructure.Decode(sourceConfig.Config, &config)

	return config, err
}
