// Code initially generated by gen.go.

package raydiumclmm

import "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/types"

type RaydiumCLMMConfig struct {
	DataSource           types.DataSourceId `json:"dataSource"`
	UpdateFrequency      string             `json:"updateFrequency"`
	HttpProviderUrl      string             `json:"httpProviderUrl"`
	ProviderApiKeyEnvVar string             `json:"providerApiKeyEnvVar"`
	ContractAddress      string             `json:"contractAddress"`
}
