package signer

// the header file is generated by cbindgen. If you can't find it, run 'make rust' in the root of this repo

/*
#cgo LDFLAGS: -L../../.lib -lsigner_ffi
#cgo CFLAGS: -I../../.lib
*/
import "C"
