package data_provider

// Autogenerated by generate_data_provider_import_file.py
import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/random"
import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/uniswap_v2"
