// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package publisher_agent

import (
	"io"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConnI creates a new instance of MockConnI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnI {
	mock := &MockConnI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnI is an autogenerated mock type for the connI type
type MockConnI struct {
	mock.Mock
}

type MockConnI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnI) EXPECT() *MockConnI_Expecter {
	return &MockConnI_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockConnI
func (_mock *MockConnI) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnI_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConnI_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConnI_Expecter) Close() *MockConnI_Close_Call {
	return &MockConnI_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConnI_Close_Call) Run(run func()) *MockConnI_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnI_Close_Call) Return(err error) *MockConnI_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnI_Close_Call) RunAndReturn(run func() error) *MockConnI_Close_Call {
	_c.Call.Return(run)
	return _c
}

// NextReader provides a mock function for the type MockConnI
func (_mock *MockConnI) NextReader() (int, io.Reader, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextReader")
	}

	var r0 int
	var r1 io.Reader
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (int, io.Reader, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() io.Reader); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConnI_NextReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextReader'
type MockConnI_NextReader_Call struct {
	*mock.Call
}

// NextReader is a helper method to define mock.On call
func (_e *MockConnI_Expecter) NextReader() *MockConnI_NextReader_Call {
	return &MockConnI_NextReader_Call{Call: _e.mock.On("NextReader")}
}

func (_c *MockConnI_NextReader_Call) Run(run func()) *MockConnI_NextReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnI_NextReader_Call) Return(messageType int, r io.Reader, err error) *MockConnI_NextReader_Call {
	_c.Call.Return(messageType, r, err)
	return _c
}

func (_c *MockConnI_NextReader_Call) RunAndReturn(run func() (int, io.Reader, error)) *MockConnI_NextReader_Call {
	_c.Call.Return(run)
	return _c
}

// NextWriter provides a mock function for the type MockConnI
func (_mock *MockConnI) NextWriter(messageType int) (io.WriteCloser, error) {
	ret := _mock.Called(messageType)

	if len(ret) == 0 {
		panic("no return value specified for NextWriter")
	}

	var r0 io.WriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (io.WriteCloser, error)); ok {
		return returnFunc(messageType)
	}
	if returnFunc, ok := ret.Get(0).(func(int) io.WriteCloser); ok {
		r0 = returnFunc(messageType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(messageType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnI_NextWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextWriter'
type MockConnI_NextWriter_Call struct {
	*mock.Call
}

// NextWriter is a helper method to define mock.On call
//   - messageType int
func (_e *MockConnI_Expecter) NextWriter(messageType interface{}) *MockConnI_NextWriter_Call {
	return &MockConnI_NextWriter_Call{Call: _e.mock.On("NextWriter", messageType)}
}

func (_c *MockConnI_NextWriter_Call) Run(run func(messageType int)) *MockConnI_NextWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnI_NextWriter_Call) Return(writeCloser io.WriteCloser, err error) *MockConnI_NextWriter_Call {
	_c.Call.Return(writeCloser, err)
	return _c
}

func (_c *MockConnI_NextWriter_Call) RunAndReturn(run func(messageType int) (io.WriteCloser, error)) *MockConnI_NextWriter_Call {
	_c.Call.Return(run)
	return _c
}

// SetReadDeadline provides a mock function for the type MockConnI
func (_mock *MockConnI) SetReadDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetReadDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnI_SetReadDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadDeadline'
type MockConnI_SetReadDeadline_Call struct {
	*mock.Call
}

// SetReadDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *MockConnI_Expecter) SetReadDeadline(t interface{}) *MockConnI_SetReadDeadline_Call {
	return &MockConnI_SetReadDeadline_Call{Call: _e.mock.On("SetReadDeadline", t)}
}

func (_c *MockConnI_SetReadDeadline_Call) Run(run func(t time.Time)) *MockConnI_SetReadDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnI_SetReadDeadline_Call) Return(err error) *MockConnI_SetReadDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnI_SetReadDeadline_Call) RunAndReturn(run func(t time.Time) error) *MockConnI_SetReadDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetWriteDeadline provides a mock function for the type MockConnI
func (_mock *MockConnI) SetWriteDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetWriteDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnI_SetWriteDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWriteDeadline'
type MockConnI_SetWriteDeadline_Call struct {
	*mock.Call
}

// SetWriteDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *MockConnI_Expecter) SetWriteDeadline(t interface{}) *MockConnI_SetWriteDeadline_Call {
	return &MockConnI_SetWriteDeadline_Call{Call: _e.mock.On("SetWriteDeadline", t)}
}

func (_c *MockConnI_SetWriteDeadline_Call) Run(run func(t time.Time)) *MockConnI_SetWriteDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnI_SetWriteDeadline_Call) Return(err error) *MockConnI_SetWriteDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnI_SetWriteDeadline_Call) RunAndReturn(run func(t time.Time) error) *MockConnI_SetWriteDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// WriteControl provides a mock function for the type MockConnI
func (_mock *MockConnI) WriteControl(messageType int, data []byte, deadline time.Time) error {
	ret := _mock.Called(messageType, data, deadline)

	if len(ret) == 0 {
		panic("no return value specified for WriteControl")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, []byte, time.Time) error); ok {
		r0 = returnFunc(messageType, data, deadline)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConnI_WriteControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteControl'
type MockConnI_WriteControl_Call struct {
	*mock.Call
}

// WriteControl is a helper method to define mock.On call
//   - messageType int
//   - data []byte
//   - deadline time.Time
func (_e *MockConnI_Expecter) WriteControl(messageType interface{}, data interface{}, deadline interface{}) *MockConnI_WriteControl_Call {
	return &MockConnI_WriteControl_Call{Call: _e.mock.On("WriteControl", messageType, data, deadline)}
}

func (_c *MockConnI_WriteControl_Call) Run(run func(messageType int, data []byte, deadline time.Time)) *MockConnI_WriteControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConnI_WriteControl_Call) Return(err error) *MockConnI_WriteControl_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConnI_WriteControl_Call) RunAndReturn(run func(messageType int, data []byte, deadline time.Time) error) *MockConnI_WriteControl_Call {
	_c.Call.Return(run)
	return _c
}
