// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package publisher_agent

import (
	"github.com/Stork-Oracle/stork-external/shared"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistryClientI creates a new instance of MockRegistryClientI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryClientI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryClientI {
	mock := &MockRegistryClientI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryClientI is an autogenerated mock type for the RegistryClientI type
type MockRegistryClientI struct {
	mock.Mock
}

type MockRegistryClientI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryClientI) EXPECT() *MockRegistryClientI_Expecter {
	return &MockRegistryClientI_Expecter{mock: &_m.Mock}
}

// GetBrokersForPublisher provides a mock function for the type MockRegistryClientI
func (_mock *MockRegistryClientI) GetBrokersForPublisher(publisherKey shared.PublisherKey) (map[BrokerPublishUrl]map[shared.AssetID]struct{}, error) {
	ret := _mock.Called(publisherKey)

	if len(ret) == 0 {
		panic("no return value specified for GetBrokersForPublisher")
	}

	var r0 map[BrokerPublishUrl]map[shared.AssetID]struct{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(shared.PublisherKey) (map[BrokerPublishUrl]map[shared.AssetID]struct{}, error)); ok {
		return returnFunc(publisherKey)
	}
	if returnFunc, ok := ret.Get(0).(func(shared.PublisherKey) map[BrokerPublishUrl]map[shared.AssetID]struct{}); ok {
		r0 = returnFunc(publisherKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[BrokerPublishUrl]map[shared.AssetID]struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(shared.PublisherKey) error); ok {
		r1 = returnFunc(publisherKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryClientI_GetBrokersForPublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBrokersForPublisher'
type MockRegistryClientI_GetBrokersForPublisher_Call struct {
	*mock.Call
}

// GetBrokersForPublisher is a helper method to define mock.On call
//   - publisherKey shared.PublisherKey
func (_e *MockRegistryClientI_Expecter) GetBrokersForPublisher(publisherKey interface{}) *MockRegistryClientI_GetBrokersForPublisher_Call {
	return &MockRegistryClientI_GetBrokersForPublisher_Call{Call: _e.mock.On("GetBrokersForPublisher", publisherKey)}
}

func (_c *MockRegistryClientI_GetBrokersForPublisher_Call) Run(run func(publisherKey shared.PublisherKey)) *MockRegistryClientI_GetBrokersForPublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 shared.PublisherKey
		if args[0] != nil {
			arg0 = args[0].(shared.PublisherKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistryClientI_GetBrokersForPublisher_Call) Return(brokerPublishUrlToAssetIDToVal map[BrokerPublishUrl]map[shared.AssetID]struct{}, err error) *MockRegistryClientI_GetBrokersForPublisher_Call {
	_c.Call.Return(brokerPublishUrlToAssetIDToVal, err)
	return _c
}

func (_c *MockRegistryClientI_GetBrokersForPublisher_Call) RunAndReturn(run func(publisherKey shared.PublisherKey) (map[BrokerPublishUrl]map[shared.AssetID]struct{}, error)) *MockRegistryClientI_GetBrokersForPublisher_Call {
	_c.Call.Return(run)
	return _c
}
