// Code initially generated by gen.go.
// This file initializes the data source and registers it, allowing it to be built by the DataProviderRunner.

package boringvaultevm

import (
	"github.com/Stork-Oracle/stork-external/apps/data_provider/pkg/sources"
	"github.com/Stork-Oracle/stork-external/apps/data_provider/pkg/types"
	"github.com/Stork-Oracle/stork-external/apps/data_provider/pkg/utils"
	"github.com/mitchellh/mapstructure"
)

var BoringVaultEvmDataSourceId types.DataSourceID = types.DataSourceID(utils.GetCurrentDirName())

type boringVaultEvmDataSourceFactory struct{}

func (f *boringVaultEvmDataSourceFactory) Build(sourceConfig types.DataProviderSourceConfig) types.DataSource {
	return newBoringVaultEvmDataSource(sourceConfig)
}

func init() {
	sources.RegisterDataSourceFactory(BoringVaultEvmDataSourceId, &boringVaultEvmDataSourceFactory{})
}

// assert we're satisfying our interfaces
var (
	_ types.DataSource        = (*boringVaultEvmDataSource)(nil)
	_ types.DataSourceFactory = (*boringVaultEvmDataSourceFactory)(nil)
)

func GetSourceSpecificConfig(sourceConfig types.DataProviderSourceConfig) (BoringVaultEvmConfig, error) {
	var config BoringVaultEvmConfig
	err := mapstructure.Decode(sourceConfig.Config, &config)

	return config, err
}
