// Code initially generated by gen.go.
// This file defines the configuration for the data source.

package polymarketprovider

import "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/types"

type PolymarketProviderConfig struct {
	DataSource      types.DataSourceId `json:"dataSource"`      // required for all Data Provider Sources
	TokenId         string             `json:"tokenId"`         // Polymarket token ID to query
	Side            string             `json:"side"`            // "buy" or "sell" side
	UpdateFrequency string             `json:"updateFrequency"` // Frequency at which updates should occur
}
