[project]
authors = ["Georgios Delkos"]
entry = "main.sw"
license = "Apache-2.0"
name = "stork_proxy"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.7.1" }