/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  stork_contract_address: Addr;
}
export type ExecuteMsg = ExecMsg;
export type ExecMsg = {
  use_stork_price: {
    feed_id: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];
  };
};
export type QueryMsg = QueryMsg1;
export type QueryMsg1 = string;