package configs

// Autogenerated by update_shared_data_provider_code.py
import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/random"
import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/uniswap_v2"
