package configs

// Autogenerated by data_provider generator
import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/random"
import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/raydiumclmm"
import _ "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/uniswapv2"

