// Code initially generated by gen.go.
// This file tests correctly loading and parsing the new source config.
package config

import (
	"testing"

	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/configs"
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/sources/polymarketprovider"
	"github.com/Stork-Oracle/stork-external/apps/lib/data_provider/utils"
	"github.com/stretchr/testify/assert"
)

func TestValidPolymarketProviderConfig(t *testing.T) {

	// TODO: set this to a valid config string using a feed from your new source
	validConfig := `
	{
	  "sources": [
		{
		  "id": "POLYMARKET_PRICE",
		  "config": {
			"dataSource": "polymarketprovider",
			"tokenId": "60487116984468020978247225474488676749601001829886755968952521846780452448915",
			"side": "buy",
			"updateFrequency": "10s"
		  }
		}
	  ]
	}`

	config, err := configs.LoadConfigFromBytes([]byte(validConfig))
	assert.NoError(t, err)

	assert.Equal(t, 1, len(config.Sources))

	sourceConfig := config.Sources[0]

	dataSourceId, err := utils.GetDataSourceId(sourceConfig.Config)
	assert.NoError(t, err)
	assert.Equal(t, polymarketprovider.PolymarketProviderDataSourceId, dataSourceId)

	sourceSpecificConfig, err := polymarketprovider.GetSourceSpecificConfig(sourceConfig)
	assert.NoError(t, err)
	assert.NotNil(t, sourceSpecificConfig)

	// TODO: write some asserts to check that the fields on sourceSpecificConfig have the values you'd expect
	assert.Equal(t, "60487116984468020978247225474488676749601001829886755968952521846780452448915", sourceSpecificConfig.TokenId)
	assert.Equal(t, "buy", sourceSpecificConfig.Side)
	assert.Equal(t, "10s", sourceSpecificConfig.UpdateFrequency)
}
