/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.100.6
  Forc version: 0.68.4
  Fuel-Core version: 0.43.2
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  EvmAddress,
  FunctionFragment,
  InvokeFunction,
  StdString,
  StrSlice,
} from 'fuels';

import type { Enum, Vec } from "./common";

export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export type StateInput = Enum<{ Uninitialized: undefined, Initialized: IdentityInput, Revoked: undefined }>;
export type StateOutput = Enum<{ Uninitialized: void, Initialized: IdentityOutput, Revoked: void }>;
export enum StorkErrorInput { InsufficientFee = 'InsufficientFee', NoFreshUpdate = 'NoFreshUpdate', FeedNotFound = 'FeedNotFound', StaleValue = 'StaleValue', InvalidSignature = 'InvalidSignature', InvalidStorkPublicKey = 'InvalidStorkPublicKey' };
export enum StorkErrorOutput { InsufficientFee = 'InsufficientFee', NoFreshUpdate = 'NoFreshUpdate', FeedNotFound = 'FeedNotFound', StaleValue = 'StaleValue', InvalidSignature = 'InvalidSignature', InvalidStorkPublicKey = 'InvalidStorkPublicKey' };
export type StorkEventInput = Enum<{ ValueUpdate: [], Initialized: undefined }>;
export type StorkEventOutput = Enum<{ ValueUpdate: [], Initialized: void }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type I128Input = { underlying: U128Input };
export type I128Output = { underlying: U128Output };
export type Secp256k1Input = { bits: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish] };
export type Secp256k1Output = { bits: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number] };
export type TemporalNumericValueInput = { timestamp_ns: BigNumberish, quantized_value: I128Input };
export type TemporalNumericValueOutput = { timestamp_ns: BN, quantized_value: I128Output };
export type TemporalNumericValueInputInput = { temporal_numeric_value: TemporalNumericValueInput, id: string, publisher_merkle_root: string, value_compute_alg_hash: string, r: string, s: string, v: BigNumberish };
export type TemporalNumericValueInputOutput = { temporal_numeric_value: TemporalNumericValueOutput, id: string, publisher_merkle_root: string, value_compute_alg_hash: string, r: string, s: string, v: number };
export type U128Input = { upper: BigNumberish, lower: BigNumberish };
export type U128Output = { upper: BN, lower: BN };

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum standards::src5::State",
      "concreteTypeId": "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
      "metadataTypeId": 2
    },
    {
      "type": "enum std::identity::Identity",
      "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      "metadataTypeId": 3
    },
    {
      "type": "enum stork_sway_sdk::errors::StorkError",
      "concreteTypeId": "475d2d1b9b9adb315310b755e85d29aa6af66cc924069dc12bf2fa5b03de5339",
      "metadataTypeId": 4
    },
    {
      "type": "enum stork_sway_sdk::events::StorkEvent",
      "concreteTypeId": "5a53bb2dd5fdf498df0233d9317f6c4235a9448fb63f5201eda779999df4ec0c",
      "metadataTypeId": 5
    },
    {
      "type": "str",
      "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
    },
    {
      "type": "struct TemporalNumericValueInput",
      "concreteTypeId": "e8a21696c4a15bbe0ae8d47a8d211519ed08608f38f3773dec46c2dc7b4a07b1",
      "metadataTypeId": 8
    },
    {
      "type": "struct std::bytes::Bytes",
      "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb",
      "metadataTypeId": 10
    },
    {
      "type": "struct std::crypto::secp256k1::Secp256k1",
      "concreteTypeId": "6d4d0ccd6814bec591db0dbab58858957ed1d2a8ff11b10068141d6fa80e6b51",
      "metadataTypeId": 13
    },
    {
      "type": "struct std::string::String",
      "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "metadataTypeId": 14
    },
    {
      "type": "struct std::vec::Vec<struct TemporalNumericValueInput>",
      "concreteTypeId": "253572200a9a05ec2068dd7b1ca0b715698384a2f2031a891048be42b845b24b",
      "metadataTypeId": 17,
      "typeArguments": [
        "e8a21696c4a15bbe0ae8d47a8d211519ed08608f38f3773dec46c2dc7b4a07b1"
      ]
    },
    {
      "type": "struct std::vm::evm::evm_address::EvmAddress",
      "concreteTypeId": "05a44d8c3e00faf7ed545823b7a2b32723545d8715d87a0ab3cf65904948e8d2",
      "metadataTypeId": 18
    },
    {
      "type": "struct stork_sway_sdk::temporal_numeric_value::TemporalNumericValue",
      "concreteTypeId": "6972e006137b782c482ffc099e21cc55fce9151a2096dd6582df22c9dc81bd9c",
      "metadataTypeId": 19
    },
    {
      "type": "struct sway_libs::signed_integers::i128::I128",
      "concreteTypeId": "800c79ceece84e53174717a2a815bd77b362c31413c682c610e5b4954b4d1c10",
      "metadataTypeId": 20
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    },
    {
      "type": "u8",
      "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
    }
  ],
  "metadataTypes": [
    {
      "type": "(_, _)",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "__tuple_element",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "__tuple_element",
          "typeId": 19
        }
      ]
    },
    {
      "type": "[_; 64]",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "__array_element",
          "typeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
        }
      ]
    },
    {
      "type": "enum standards::src5::State",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Uninitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Initialized",
          "typeId": 3
        },
        {
          "name": "Revoked",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "Address",
          "typeId": 9
        },
        {
          "name": "ContractId",
          "typeId": 12
        }
      ]
    },
    {
      "type": "enum stork_sway_sdk::errors::StorkError",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "InsufficientFee",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NoFreshUpdate",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "FeedNotFound",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "StaleValue",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidSignature",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidStorkPublicKey",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum stork_sway_sdk::events::StorkEvent",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "ValueUpdate",
          "typeId": 0
        },
        {
          "name": "Initialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "generic T",
      "metadataTypeId": 6
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 7
    },
    {
      "type": "struct TemporalNumericValueInput",
      "metadataTypeId": 8,
      "components": [
        {
          "name": "temporal_numeric_value",
          "typeId": 19
        },
        {
          "name": "id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "publisher_merkle_root",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "value_compute_alg_hash",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "r",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "s",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "v",
          "typeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 9,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "buf",
          "typeId": 11
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "ptr",
          "typeId": 7
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 12,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::crypto::secp256k1::Secp256k1",
      "metadataTypeId": 13,
      "components": [
        {
          "name": "bits",
          "typeId": 1
        }
      ]
    },
    {
      "type": "struct std::string::String",
      "metadataTypeId": 14,
      "components": [
        {
          "name": "bytes",
          "typeId": 10
        }
      ]
    },
    {
      "type": "struct std::u128::U128",
      "metadataTypeId": 15,
      "components": [
        {
          "name": "upper",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "lower",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct std::vec::RawVec",
      "metadataTypeId": 16,
      "components": [
        {
          "name": "ptr",
          "typeId": 7
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        6
      ]
    },
    {
      "type": "struct std::vec::Vec",
      "metadataTypeId": 17,
      "components": [
        {
          "name": "buf",
          "typeId": 16,
          "typeArguments": [
            {
              "name": "",
              "typeId": 6
            }
          ]
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        6
      ]
    },
    {
      "type": "struct std::vm::evm::evm_address::EvmAddress",
      "metadataTypeId": 18,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct stork_sway_sdk::temporal_numeric_value::TemporalNumericValue",
      "metadataTypeId": 19,
      "components": [
        {
          "name": "timestamp_ns",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "quantized_value",
          "typeId": 20
        }
      ]
    },
    {
      "type": "struct sway_libs::signed_integers::i128::I128",
      "metadataTypeId": 20,
      "components": [
        {
          "name": "underlying",
          "typeId": 15
        }
      ]
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "get_temporal_numeric_value_unchecked_v1",
      "output": "6972e006137b782c482ffc099e21cc55fce9151a2096dd6582df22c9dc81bd9c",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "update_data",
          "concreteTypeId": "253572200a9a05ec2068dd7b1ca0b715698384a2f2031a891048be42b845b24b"
        }
      ],
      "name": "get_update_fee_v1",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "initial_owner",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "stork_public_key",
          "concreteTypeId": "05a44d8c3e00faf7ed545823b7a2b32723545d8715d87a0ab3cf65904948e8d2"
        },
        {
          "name": "single_update_fee_in_wei",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "initialize",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "single_update_fee_in_wei",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "stork_public_key",
      "output": "05a44d8c3e00faf7ed545823b7a2b32723545d8715d87a0ab3cf65904948e8d2",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "single_update_fee_in_wei",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "update_single_update_fee_in_wei",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "stork_public_key",
          "concreteTypeId": "05a44d8c3e00faf7ed545823b7a2b32723545d8715d87a0ab3cf65904948e8d2"
        }
      ],
      "name": "update_stork_public_key",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "update_data",
          "concreteTypeId": "253572200a9a05ec2068dd7b1ca0b715698384a2f2031a891048be42b845b24b"
        }
      ],
      "name": "update_temporal_numeric_values_v1",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "stork_pubkey",
          "concreteTypeId": "05a44d8c3e00faf7ed545823b7a2b32723545d8715d87a0ab3cf65904948e8d2"
        },
        {
          "name": "id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "recv_time",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "quantized_value",
          "concreteTypeId": "800c79ceece84e53174717a2a815bd77b362c31413c682c610e5b4954b4d1c10"
        },
        {
          "name": "publisher_merkle_root",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "value_compute_alg_hash",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "r",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "s",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "v",
          "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
        }
      ],
      "name": "verify_stork_signature_v1",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    },
    {
      "inputs": [],
      "name": "version",
      "output": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "attributes": null
    },
    {
      "inputs": [],
      "name": "owner",
      "output": "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "5142315946124958513",
      "concreteTypeId": "475d2d1b9b9adb315310b755e85d29aa6af66cc924069dc12bf2fa5b03de5339"
    },
    {
      "logId": "10098701174489624218",
      "concreteTypeId": "8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a"
    },
    {
      "logId": "8961848586872524460",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "logId": "14832741149864513620",
      "concreteTypeId": "cdd87b7d12fe505416570c294c884bca819364863efe3bf539245fa18515fbbb"
    },
    {
      "logId": "7875965399694884549",
      "concreteTypeId": "6d4d0ccd6814bec591db0dbab58858957ed1d2a8ff11b10068141d6fa80e6b51"
    },
    {
      "logId": "406535131101199095",
      "concreteTypeId": "05a44d8c3e00faf7ed545823b7a2b32723545d8715d87a0ab3cf65904948e8d2"
    },
    {
      "logId": "6508751692018611352",
      "concreteTypeId": "5a53bb2dd5fdf498df0233d9317f6c4235a9448fb63f5201eda779999df4ec0c"
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [
  {
    "key": "6189f6fb2b7278c2a5f1b1ebfc35d4838d6c414acd1f700a7cf63bfc75e71a2b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "6189f6fb2b7278c2a5f1b1ebfc35d4838d6c414acd1f700a7cf63bfc75e71a2c",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "cc810296276c1a8f95a9839c890da0814ec4cd69701f777654be6d879ad0e372",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "f565ddf302f385048492da91a5ab6b089740abdfd5915ce000d038ad2b0b926e",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "f565ddf302f385048492da91a5ab6b089740abdfd5915ce000d038ad2b0b926f",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "fb81ee288c2f1b5e5ca789e7660af75cf181385e66e41017f0abb13b5ff1660d",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class StorkInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    get_temporal_numeric_value_unchecked_v1: FunctionFragment;
    get_update_fee_v1: FunctionFragment;
    initialize: FunctionFragment;
    single_update_fee_in_wei: FunctionFragment;
    stork_public_key: FunctionFragment;
    update_single_update_fee_in_wei: FunctionFragment;
    update_stork_public_key: FunctionFragment;
    update_temporal_numeric_values_v1: FunctionFragment;
    verify_stork_signature_v1: FunctionFragment;
    version: FunctionFragment;
    owner: FunctionFragment;
  };
}

export class Stork extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: StorkInterface;
  declare functions: {
    get_temporal_numeric_value_unchecked_v1: InvokeFunction<[id: string], TemporalNumericValueOutput>;
    get_update_fee_v1: InvokeFunction<[update_data: Vec<TemporalNumericValueInputInput>], BN>;
    initialize: InvokeFunction<[initial_owner: IdentityInput, stork_public_key: EvmAddress, single_update_fee_in_wei: BigNumberish], void>;
    single_update_fee_in_wei: InvokeFunction<[], BN>;
    stork_public_key: InvokeFunction<[], EvmAddress>;
    update_single_update_fee_in_wei: InvokeFunction<[single_update_fee_in_wei: BigNumberish], void>;
    update_stork_public_key: InvokeFunction<[stork_public_key: EvmAddress], void>;
    update_temporal_numeric_values_v1: InvokeFunction<[update_data: Vec<TemporalNumericValueInputInput>], void>;
    verify_stork_signature_v1: InvokeFunction<[stork_pubkey: EvmAddress, id: string, recv_time: BigNumberish, quantized_value: I128Input, publisher_merkle_root: string, value_compute_alg_hash: string, r: string, s: string, v: BigNumberish], boolean>;
    version: InvokeFunction<[], StdString>;
    owner: InvokeFunction<[], StateOutput>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
