[package]
name = "signer_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
starknet-core = "0.9.0"
hex = "0.4.3"
eth-encode-packed = "0.1.0"

[build-dependencies]
cargo_metadata = "0.22.0"
cbindgen = "0.24.0"
