[package]
name = "example"
version = "1.0.0"
authors = []

[addresses]
example = "_"
# Official addresses can be found at https://docs.stork.network/resources/contract-addresses/initia_minimove
stork = "0x68ba7261bf09152006999d7f53432ed540e238d8f1050e1fe739738309f58217"

[dev-addresses]
example = "0x101"

[dependencies.InitiaStdlib]
git = "https://github.com/initia-labs/movevm.git"
rev = "main"
subdir = "precompile/modules/initia_stdlib"

[dependencies.stork]
git = "https://github.com/stork-oracle/stork-external.git"
rev = "main"
subdir = "chains/initia_minimove/contracts"

[dev-dependencies]
