package configs

// Autogenerated by data_provider generator
import (
	_ "github.com/Stork-Oracle/stork-external/apps/data_provider/lib/sources/boringvaultevm"
	_ "github.com/Stork-Oracle/stork-external/apps/data_provider/lib/sources/random"

	_ "github.com/Stork-Oracle/stork-external/apps/data_provider/lib/sources/raydiumclmm"

	_ "github.com/Stork-Oracle/stork-external/apps/data_provider/lib/sources/uniswapv2"
)
