name: Clear Go Cache

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Go cache
        uses: actions/github-script@v7
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            for (const cache of caches.data.actions_caches) {
              if (cache.key.includes('-go-')) {
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id
                });
                console.log(`Deleted cache: ${cache.key}`);
              }
            }

      - name: Notify completion
        run: echo "Go cache has been cleared. You can now re-run your CI workflow." 