// Code initially generated by gen.go.
// This file defines the configuration for the data source.

package monadtokenprice

import "github.com/Stork-Oracle/stork-external/apps/lib/data_provider/types"

type MonadTokenPriceConfig struct {
	DataSource      types.DataSourceId `json:"dataSource"` // required for all Data Provider Sources
	RpcEndpoint     string             `json:"rpcEndpoint"` // Monad RPC endpoint URL
	UpdateFrequency string             `json:"updateFrequency"` // How often to fetch token prices
	RouterAddress   string             `json:"routerAddress"` // DEX router contract address
	TokenAddress    string             `json:"tokenAddress"` // Token contract address
	BaseTokenAddress string            `json:"baseTokenAddress"` // Base token address (e.g., USDC)
}
