// Code initially generated by gen.go.
// This file contains unit tests for functions implemented in the data source.

package monadtokenprice

import (
	"testing"
)

func TestMonadTokenPriceDataSource(t *testing.T) {
	// TODO: write some unit tests for your data source
	t.Fatalf("implement me")
}
